project:
  type: website
  output-dir: _site

website:
  description: "Insang Song's Blog"
  site-url: https://sigmafelix.github.io
  title: "Spin rules"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
    css: styles.css



